---
title: "index"
author: "Yan Wang"
date: "2023-10-02"
output: html_document
---

```{r setup, echo=TRUE}
library(here)
if (!file.exists(here("data", "b_lyrics.RDS"))) {
    b_lyrics <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/beyonce_lyrics.csv")
    ts_lyrics <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/taylor_swift_lyrics.csv")
    sales <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/sales.csv")

    # save the files to RDS objects
    saveRDS(b_lyrics, file = here("data", "b_lyrics.RDS"))
    saveRDS(ts_lyrics, file = here("data", "ts_lyrics.RDS"))
    saveRDS(sales, file = here("data", "sales.RDS"))
}
b_lyrics <- readRDS(here("data", "b_lyrics.RDS"))
ts_lyrics <- readRDS(here("data", "ts_lyrics.RDS"))
sales <- readRDS(here("data", "sales.RDS"))
```

## Part 1: Explore album sales
### Part1A
```{r, echo=TRUE}
library(tidyverse)
library(lubridate)
library(stringr)
library(forcats)
sales1 <- mutate(sales, released = str_remove(released, "\\([A-Z]{2}\\)\\[\\d+\\]"))
sales2 <- mutate(sales1, released = mdy(released))
sales3 <- mutate(sales2, country = fct_collapse(country, "World" = c("World", "WW"), "FRA" = c("FRA", "FR")))
sales4 <- mutate(sales3, sales = sales/1000000)
sales5 <- filter(sales4, country %in% c ("US", "UK", "World"))
print(sales5)
```

### Part1B
```{r, echo=TRUE}
sales6 <- filter(sales5, country == "US")
sales7 <- mutate(sales6, years_since_release = floor(interval(released, Sys.Date())/duration(num = 1, units = "years")))
sales7 %>% group_by(artist) %>% summarize(most_recent = min(years_since_release), most_oldest = max(years_since_release), median_years = median(years_since_release)) %>% print()
```

### Part1C
```{r, echo=TRUE}
sales6 <- sales5 %>% group_by(artist, country) %>% summarize(total_album_sales = sum(sales)) %>% print()
sales7 <- sales6 %>% group_by(artist) %>% mutate(percentages = total_album_sales / sum(total_album_sales) * 100)
print(sales7)
library(ggplot2)
ggplot(sales7, aes(x = artist, y = percentages, fill = country)) + 
  geom_col(position = "fill") + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Percentages of album sales (in millions) for Beyonce and Taylor Swift", subtitle = "Different countries have different percentages", x = "Artists", y = "Percentages of album sales in different counties", fill = "country", caption = "By Yan Wang") + theme_classic() + theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), plot.caption = element_text(size = 16, face = "bold"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13)) + ThemePark::theme_friends()
```

### Part1D:
```{r}
library(forcats)
library(dplyr)
sales8 <- sales5 %>% filter(country == "World") %>% arrange(desc(sales)) %>% mutate(title = fct_reorder(title, sales))
ggplot(sales8, aes(x = sales, y = title, fill = artist)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Ranking of album sales all over the world",
       subtitle = "For Taylor, Fearless is best sold \nFor Beyonce, Dangerously in Love is best sold", 
       x = "Sales (in millions)",
       y = "Album",
       fill = "artist") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13))
```
### Part1E
```{r, echo=TRUE}
ggplot(sales5, aes(x = released, y = sales, color = artist)) +
  geom_point() +
  facet_wrap(~country, nrow = 3) +
  labs(
    title = "Album sales over released date",
    subtitle = "Album sales changes in a wave-like manner",
    x = "Released data",
    y = "Sales (in millions)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13))
```

## Part 2: Exploring sentiment of lyrics
### Part2A
```{r}
library(tidytext)
library(tidyr)
ts_lyrics1 <- unnest_tokens(ts_lyrics, output = line, input = Lyrics, token = "lines")
hello_ts_lyrics <- ts_lyrics1 %>% filter(str_detect(line, "hello"))
nrow(hello_ts_lyrics)
goodbye_ts_lyrics <- ts_lyrics1 %>% filter(str_detect(line, "goodbye"))
nrow(goodbye_ts_lyrics)
```
### Part2B
```{r, echo=TRUE}
b_lyrics1 <- unnest_tokens(b_lyrics, output = line, input = line, token = "lines")
hello_b_lyrics <- b_lyrics1 %>% filter(str_detect(line, "hello"))
nrow(hello_b_lyrics)
goodbye_b_lyrics <- b_lyrics1 %>% filter(str_detect(line, "goodbye"))
nrow(goodbye_b_lyrics)
```
### Part2C
```{r, echo=TRUE}
b_lyrics2 <- b_lyrics %>% unnest_tokens(output = word, input = line, token = "words") %>% anti_join(stop_words)
word_counts <- count(b_lyrics2, word, sort = TRUE)
bing <- get_sentiments("bing")
word_counts1 <- inner_join(word_counts, bing, by = "word")
word_counts2 <- arrange(word_counts1, desc(n))
top25 <- head(word_counts2, 25)
print(top25)
ggplot(top25, aes(x = n, y = fct_reorder(word, n), fill = sentiment)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("positive" = "yellow", "negative" = "pink")) +
  labs(title = "Top 25 words for Beyonce lyrics", subtitle = "Love is the top 1", x = "Frequency", y = "Words") + 
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13))
library(wordcloud)
wordcloud(words = top25$word, freq = top25$n, scale = c(5, 0.5), colors = brewer.pal(12, "RdYlBu"))
```

### Part2D
```{r, echo=TRUE}
ts_lyrics2 <- ts_lyrics %>% unnest_tokens(output = word, input = Lyrics, token = "words") %>% anti_join(stop_words)
ts_word_count <- count(ts_lyrics2, word, sort = TRUE)
ts_word_count1 <- inner_join(ts_word_count, bing, by = "word")
ts_word_count2 <- arrange(ts_word_count1, desc(n))
ts_top25 <- head(ts_word_count2, 25)
print(ts_top25)
ggplot(ts_top25, aes(x = n, y = fct_reorder(word, n), fill = sentiment)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("positive" = "#FF4500", "negative" = "#C0C0C0")) +
  labs(title = "Top 25 words for Taylor Swift lyrics", subtitle = "Love is the top 1", x = "Frequency", y = "Words") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13))
wordcloud(words = ts_top25$word, freq = ts_top25$n, scale = c(5, 0.5), colors = brewer.pal(12, "PiYG"))
```

### Part2E:
```{r, echo=TRUE}
ts_word_count3 <- ts_lyrics2 %>% group_by(Album) %>% count(word, sort = TRUE)
afinn <- get_sentiments("afinn")
ts_word_count4 <- left_join(ts_word_count3, afinn)
average_value <- ts_word_count4 %>% group_by(Album) %>% summarize(average = mean(value, na.rm = TRUE))
print(average_value)
new <- rename(average_value, title = Album)
newsales <- left_join(sales5, new, by = "title")
ggplot(newsales, aes(x = released, y = average, size = sales)) + 
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "green") +
  labs(title = "Average Sentiment Score of Taylor Swift's Albums Over Time", subtitle = "Most average socres are negative.", x = "Released date", y = "Average scores", size = "Sales (in millions)") +
  theme_classic() +
  theme(plot.title = element_text(size = 16, face = "bold"), plot.subtitle = element_text(size = 11, face = "italic"), legend.position = "right", legend.text = element_text(size = 11), legend.title = element_text(size = 13)) +
  ThemePark::theme_friends()
```

